// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0Nn4r_xrE_MhpmSqAxe6yHUzEuCMVF8Y',
    appId: '1:424414757289:web:11a1659e4b5ae37ba884b8',
    messagingSenderId: '424414757289',
    projectId: 'loredo-64837',
    authDomain: 'loredo-64837.firebaseapp.com',
    storageBucket: 'loredo-64837.firebasestorage.app',
    measurementId: 'G-KF20BQ6J0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN_8FmUnQAVZxLg1wERPgIwJOonntCIuU',
    appId: '1:424414757289:android:da14546b02b29fefa884b8',
    messagingSenderId: '424414757289',
    projectId: 'loredo-64837',
    storageBucket: 'loredo-64837.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8KyL5dyyapiYC_Y3LQnE6B2to2tjBeS0',
    appId: '1:424414757289:ios:60d89ceab711065aa884b8',
    messagingSenderId: '424414757289',
    projectId: 'loredo-64837',
    storageBucket: 'loredo-64837.firebasestorage.app',
    iosBundleId: 'com.example.loredoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8KyL5dyyapiYC_Y3LQnE6B2to2tjBeS0',
    appId: '1:424414757289:ios:60d89ceab711065aa884b8',
    messagingSenderId: '424414757289',
    projectId: 'loredo-64837',
    storageBucket: 'loredo-64837.firebasestorage.app',
    iosBundleId: 'com.example.loredoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0Nn4r_xrE_MhpmSqAxe6yHUzEuCMVF8Y',
    appId: '1:424414757289:web:18368602a919a327a884b8',
    messagingSenderId: '424414757289',
    projectId: 'loredo-64837',
    authDomain: 'loredo-64837.firebaseapp.com',
    storageBucket: 'loredo-64837.firebasestorage.app',
    measurementId: 'G-5F9XC1YSGB',
  );
}
